services:
  database:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5488:5432"
    networks:
      - app_net

  volter:
    build: .
    depends_on:
      - database
    environment:
      - ENV_MODE=production
    env_file:
      - .env
    volumes:
      - .:/aplikasi
    command: [ "python", "-u", "main.py" ]
    networks:
      - app_net

volumes:
  pgdata:


networks:
  app_net:
    driver: bridge
